module HAMMING_IP#(parameter IP_BIT = 8)(
    IN_code,
    OUT_code
);
input [IP_BIT+4-1 : 0]IN_code;
output reg [IP_BIT-1 : 0]OUT_code;

localparam CODE_BIT = IP_BIT + 4;


wire reverse_data[CODE_BIT-1:0];
wire [3:0]pos_store[CODE_BIT-1:0];
wire [3:0]tmp[CODE_BIT-2:0];
//  =========== REFERENCE ==========
//position 1 2 3 4 5 6 7 8
//pos[i]   0 1 2 3 4 5 6 7
//real_pos 7 6 5 4 3 2 1 0
//data     1 1 0 0 1 0 1 1
//pos_store => store position which contain 1's.


genvar i;
generate
    for(i = 0; i<CODE_BIT; i= i+1)begin
        assign reverse_data[i] = IN_code[CODE_BIT-1-i];
    end
endgenerate

genvar j;
generate
    for(j = 0; j<CODE_BIT;  j = j+1)begin
        assign pos_store[j] = (reverse_data[j])?j+1:0;
    end
endgenerate

genvar k;
generate
    for(k=0 ; k < CODE_BIT -1; k  = k+1 )begin
        if(k==0)begin
            assign tmp[k] = pos_store[0] ^ pos_store[1];
        end
        else begin
            assign tmp[k] = pos_store[k+1] ^ tmp[k-1];
        end 
    end
endgenerate

wire [3:0] error_bit;
wire [3:0]real_bit;
reg[CODE_BIT-1:0]decode_data;
// error bit generated by XOR above
assign error_bit = tmp[CODE_BIT-2];

//reverse to real bit
assign real_bit = CODE_BIT - error_bit;

// error bit fix
genvar k;
generate
    for(k=0;k<CODE_BIT;k=k+1) begin 
        always @(*) begin
            if(k == real_bit)
                decode_data[k] = ~IN_code[k];
            else
                decode_data[k] = IN_code[k];
        end
    end
endgenerate

always @(*) begin
    OUT_code = {decode_data[CODE_BIT-3], decode_data[CODE_BIT-5], decode_data[CODE_BIT-6], decode_data[CODE_BIT-7],
                decode_data[CODE_BIT-9 : 0]};
end

 
endmodule
